"""Marimo notebook: quick sanity-check views over the example corpus.

Run interactively with `marimo edit nbks/corpus_analysis.py`, or as a static
app with `make nbks-corpus` (== `marimo run nbks/corpus_analysis.py`) from the
project root — the relative paths below assume that cwd.

NOTE (uncertain, flagged for review): this file was hand-written rather than
generated by `marimo edit`/`marimo new`, because marimo wasn't installed in
the environment this was authored in, so the cell wiring below could not be
verified by actually running it. The parts most likely to need a fix if
`marimo run`/`marimo edit` complains:
  - The exact `@app.cell` function signature/return-tuple wiring (inputs =
    names of variables produced by other cells; returns = tuple of names
    this cell defines that other cells consume). The shape matches marimo's
    documented file format as of the 0.13.x series.
  - Whether `mo.ui.table(list_of_dicts, label=...)` is the right call for
    rendering a plain list of dicts as a table (vs. needing a
    pandas/polars DataFrame). No pandas dependency is declared in
    pyproject.toml's `notebooks` group, so this intentionally avoids pandas.
  - `marimo.App(width="medium")` — a real constructor kwarg as of recent
    marimo versions, but not re-verified here.
"""

from __future__ import annotations

import marimo

__generated_with = "0.13.3"
app = marimo.App(width="medium")


@app.cell
def _():
    import marimo as mo

    return (mo,)


@app.cell
def _(mo):
    mo.md("# Corpus analysis")
    return


@app.cell
def _():
    import json
    from collections import Counter
    from pathlib import Path

    from core.ingestion import load_raw_articles

    return Counter, Path, json, load_raw_articles


@app.cell
def _(Path, load_raw_articles):
    articles = load_raw_articles(Path("data/corpus"))
    return (articles,)


@app.cell
def _(mo):
    mo.md("## Articles (id, title, word count)")
    return


@app.cell
def _(articles, mo):
    article_rows = [
        {
            "id": article.id,
            "title": article.title,
            "word_count": len(article.text.split()),
        }
        for article in articles
    ]
    mo.ui.table(article_rows, label="Corpus articles")
    return (article_rows,)


@app.cell
def _(Path, json):
    golden_qa_path = Path("data/corpus/golden_qa.jsonl")
    golden_qa = [
        json.loads(line)
        for line in golden_qa_path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    return (golden_qa,)


@app.cell
def _(mo):
    mo.md("## Golden QA category distribution")
    return


@app.cell
def _(Counter, golden_qa, mo):
    category_counts = Counter(row["category"] for row in golden_qa)
    category_rows = [
        {"category": category, "count": count}
        for category, count in sorted(category_counts.items(), key=lambda item: -item[1])
    ]
    mo.ui.table(category_rows, label="Category distribution")
    return (category_rows,)


if __name__ == "__main__":
    app.run()
